name: Build Docker Image to Docker Hub
on: 
  push:
    branches:
      - main
      - master
permissions:
  id-token: write
  contents: read
jobs:
  deployment:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Environment Setup
        run: |
          echo "export const environment = {" >> src/environments/environment.ts
          echo "API_URL: '${{ secrets.API_URL }}'," >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts
          echo "export const environment = {" >> src/environments/environment.development.ts
          echo "API_URL: '${{ secrets.API_URL }}'," >> src/environments/environment.development.ts
          echo "};" >> src/environments/environment.development.ts
          cat src/environments/environment.development.ts 

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Container
        env:
          REGISTRY: ${{ vars.REGISTRY }}
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          GITHUB_SHA: ${{ github.sha }}
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USER }}
        run: |
          docker build -t $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA .
          docker tag $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
          docker push $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA
          docker push $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Deploy to AWS
        uses: fdiesel/github-action-deploy-aws-lightsail-container@v3.0.1
        with:
          image-name: ${{vars.IMAGE_NAME}}
          image: ${{vars.REGISTRY}}/${{vars.IMAGE_NAME}}:${{github.sha}}
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-lightsail-service: ${{ vars.AWS_LIGHTSAIL_SERVICE }}
          aws-lightsail-service-config: ${{ secrets.AWS_LIGHTSAIL_SERVICE_CONFIG }}
          aws-lightsail-clear-images: true