name: Build Docker Image to Docker Hub
on: 
  push:
    branches:
      - main
      - master
permissions:
  id-token: write
  contents: read
jobs:
  deployment:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Environment Setup
        run: |
          echo "export const environment = {" >> src/environments/environment.ts
          echo "API_URL: '${{ secrets.API_URL }}'," >> src/environments/environment.ts
          echo "};" >> src/environments/environment.ts

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        env:
          USERNAME: ${{ secrets.REGISTRY_USER }}
          PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        with:
          username: $USERNAME
          password: $PASSWORD

      - name: Build Container
        env:
          REGISTRY: ${{ vars.REGISTRY }}
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          GITHUB_SHA: ${{ github.sha }}
          DOCKER_USERNAME: ${{ secrets.REGISTRY_USER }}
        run: |
          docker build -t $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA .
          docker tag $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
          docker push $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA
          docker push $REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest